# Generated by Django 3.1.5 on 2021-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
