# Generated by Django 3.1.5 on 2021-01-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0002_auto_20210130_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numd', models.IntegerField(default=0)),
                ('oQd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disliked', to='mainpg.question')),
            ],
        ),
    ]
