# Generated by Django 3.1.5 on 2021-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0003_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='numd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='num',
            field=models.IntegerField(),
        ),
    ]
