# Generated by Django 3.1.5 on 2021-01-31 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpg', '0005_auto_20210130_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansrs', to=settings.AUTH_USER_MODEL)),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allans', to='mainpg.question')),
            ],
        ),
    ]
