# Generated by Django 3.1.5 on 2021-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='originaldp',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
