# Generated by Django 3.1.5 on 2021-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0002_auto_20210212_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.png', upload_to='profilepics'),
        ),
    ]
