# Generated by Django 3.1.5 on 2021-02-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('mainpg', '0003_auto_20210213_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.ManyToManyField(related_name='followings', to='socialaccount.SocialAccount')),
                ('usrtf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuser', to='socialaccount.socialaccount')),
            ],
        ),
    ]
