# Generated by Django 3.1.5 on 2021-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0004_followlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
