# Generated by Django 3.1.5 on 2021-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0004_auto_20210130_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
