# Generated by Django 3.1.5 on 2021-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0005_auto_20210215_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='Github_Handle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='insta',
            new_name='Instagram_Handle',
        ),
        migrations.AddField(
            model_name='profile',
            name='Linkedin_Handle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Twitter_Handle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
