# Generated by Django 3.1.5 on 2021-02-03 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpg', '0007_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissaved', to=settings.AUTH_USER_MODEL)),
                ('ofQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked', to='mainpg.question')),
            ],
        ),
    ]
